apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: demo-0
spec:
  flows:
    - route:
        id: demo-route-0
        group: demo-group-0
        from:
          uri: "timer:exception"
          id: timer-exception-0
          parameters:
            period: '10000'
          steps:
            - setBody:
                constant: "Hello Camel K from yaml"
            - to:
                uri: "log:info?showAll=true&multiline=true"
                id: log-info-0
  traits:
    addons:
      telemetry:
        enabled: true
        endpoint: http://jaeger-collector:4317
    logging:
      enabled: true
      json: true
